### ISSUE TITLE
from nnieqat.modules import convert_layers  error

### ISSUE THREAD

**Issue by zyc4me** [aovoc/nnieqat-pytorch#1]
OSError: /usr/local/cuda-10.0/lib64/libcublas.so.10: version `libcublas.so.10' not found (required by /home/xxx/anaconda3/envs/xxx_py36/lib/python3.6/site-packages/nnieqat/gpu/lib/libgfpq_gpu.so)

how do i solve this?

**Comment by aovoc** [comment]
You have to install cuda10 driver. Cublas is an implementation of blas(basic linear algebra subroutine) library on cuda.

**Comment by zyc4me** [comment]
> You have to install cuda10 driver. Cublas is an implementation of blas(basic linear algebra subroutine) library on cuda.

thank you for your reply。
cuda-10.0 is installed， and i modified &source ~/.baschrc, 
run nvcc -V comand get this  Cuda compilation tools, release 10.0, V10.0.130

**Comment by aovoc** [comment]
great!

**Comment by zyc4me** [comment]
> You have to install cuda10 driver. Cublas is an implementation of blas(basic linear algebra subroutine) library on cuda.

sorry, - -,i mean i already do this installation before run from nnieqat.modules import convert_layers, still exist this error

**Comment by aovoc** [comment]
Test whether cublas library is installed correctlly or not with:
```shell
file /usr/local/cuda-10.0/lib64/libcublas.so.10
ldd /usr/local/cuda-10.0/lib64/libcublas.so.10
```  

A easy way to avoid this problem is installing nnieqat in a docker， I have updated relative installation info in ReadMe.

**Comment by aovoc** [comment]
#2
