### ISSUE TITLE
error when i run the "from nnieqat import quant_dequant_weight"

### ISSUE THREAD

**Issue by zj19921221** [aovoc/nnieqat-pytorch#10]
hi I met a error when i run the "from nnieqat import quant_dequant_weight"

error information is shown as "ImportError: cannot import name 'quant_dequant_weight'" 

when i run the "import nnieqat" it is ok 

Can you give me some help!

thanks a lot!

**Comment by aovoc** [comment]
I do not update public pypi  package yet,  try installing the package via repo.
