### ISSUE TITLE
量化感知训练后如何在使用nnie_mapper工具转换？

### ISSUE THREAD

**Issue by KarlQu1990** [aovoc/nnieqat-pytorch#16]
你好，我使用这个框架finetune训练了yolov3模型，想问一下训练完的权重如何结合nnie_mapper使用？我看到你在知乎的评论回复中说“可以读取并关联pytorch模型和转换后caffe模型的对应层，然后将量化信息写到nnie_mapper cfg的gfpq_param_file里边哈”，我在nnie_mapper参数表里没有看到gfpq_param_file这个参数说明，能不能再详细的讲一下部署的过程？
感谢！

**Comment by tensorflowt** [comment]
> 你好，我使用这个框架finetune训练了yolov3模型，想问一下训练完的权重如何结合nnie_mapper使用？我看到你在知乎的评论回复中说“可以读取并关联pytorch模型和转换后caffe模型的对应层，然后将量化信息写到nnie_mapper cfg的gfpq_param_file里边哈”，我在nnie_mapper参数表里没有看到gfpq_param_file这个参数说明，能不能再详细的讲一下部署的过程？
> 感谢！

请问你这个问题解决了吗？

**Comment by KarlQu1990** [comment]
> > 你好，我使用这个框架finetune训练了yolov3模型，想问一下训练完的权重如何结合nnie_mapper使用？我看到你在知乎的评论回复中说“可以读取并关联pytorch模型和转换后caffe模型的对应层，然后将量化信息写到nnie_mapper cfg的gfpq_param_file里边哈”，我在nnie_mapper参数表里没有看到gfpq_param_file这个参数说明，能不能再详细的讲一下部署的过程？
> > 感谢！
> 
> 请问你这个问题解决了吗？

没有，最后没有用到量化感知训练，直接使用的nnie_mapper量化。

**Comment by aovoc** [comment]
gfpq_param_file 选项在较新版本的 nnie_mapper 里边有，查看nnie_mapper 更新说明可找到哈。

**Comment by KarlQu1990** [comment]
多谢回复。我这边用的是3559a的板子，对应nnie_mapper 1.1版本，可能用不了较新的版本。

**Comment by Timothy-105** [comment]
量化感知训练后将模型部署在hisi平台，pytorch -onnx-caffe的过程中，相比原来的模型，onnx在卷积激活后会多出一个cast层，caffe不支持，请问可有解决的办法？

**Comment by aovoc** [comment]
> 量化感知训练后将模型部署在hisi平台，pytorch -onnx-caffe的过程中，相比原来的模型，onnx在卷积激活后会多出一个cast层，caffe不支持，请问可有解决的办法？

可以试试走pytorch-caffe 的流程哈

**Comment by dmuqlzhang** [comment]
> 量化感知训练后将模型部署在hisi平台，pytorch -onnx-caffe的过程中，相比原来的模型，onnx在卷积激活后会多出一个cast层，caffe不支持，请问可有解决的办法？

请问cast层问题解决了吗

**Comment by KarlQu1990** [comment]
已收到您的邮件，谢谢！
