### ISSUE TITLE
你好！我需要如何使用nnieqat在我自己的工程中呢？

### ISSUE THREAD

**Issue by tensorflowt** [aovoc/nnieqat-pytorch#17]
你好！
非常感谢你分享的nnieqat的相关工作。
目前，我在使用海思的3519芯片移植目标检测算法yolov3。目前遇到的问题是模型经过int8量化之后精度损失比较严重，因此想参考你的工作做模型的量化工作。
我不确定我对你的工作中提到的方法的使用的正确性，因此我想简单陈述一下我的理解（以v5为例），具体如下：
1）通过nnieqat量化库 fine-tuning一个训练好的基于pytorch框架的yolov5模型，之后得到了一个基于int8量化后的模型文件
2）关联pytorch模型和转换后caffe模型的对应层信息
3）将量化信息写到nnie_mapper cfg的gfpq_param_file中
4）如何转为wk模型文件？

谢谢博主！

**Comment by aovoc** [comment]
模型量化可分为权重量化和激活层量化。对于权重量化，在量化finetune 过程中会使得权重符合nnie的量化特性，使用nniemapper 量化的结果符合我们的预期，权重量化算法可见[NNIE量化算法及实现](https://zhuanlan.zhihu.com/p/223018242
)；对于激活层量化，可以映射量化信息到转换后的模型的对应层，将信息写入gfpq_param_file 文件中。
因此，转为wk模型文件可以用nniemapper来进行，欢迎交流指正～

**Comment by 0-LL-0** [comment]
@aovoc 哥，您好！最近在用Hisi量化，遇到了损失较大的问题。知乎上翻到了您的文章。非常感谢您的分享。
我还是有些不太清楚的地方，向您请教一下。
（1）权重量化部分：流程和以前一样：先把pytorch->转为caffe模型，使用nniemapper转换为wk。只是模型替换成依赖nnieqat训练的新模型？
（2）激活层量化部分：这个点，我的疑惑比较多，期望您的解惑
a：激活层量化是统计每个中间输出层中的绝对值最大的数值吗？
b：是基于单张图统计，还是随机抽取多张样本，批量前向，然后进行汇总统计？

**Comment by shinianzhihou** [comment]
> 模型量化可分为权重量化和激活层量化。对于权重量化，在量化finetune 过程中会使得权重符合nnie的量化特性，使用nniemapper 量化的结果符合我们的预期，权重量化算法可见[NNIE量化算法及实现](https://zhuanlan.zhihu.com/p/223018242)；对于激活层量化，可以映射量化信息到转换后的模型的对应层，将信息写入gfpq_param_file 文件中。 因此，转为wk模型文件可以用nniemapper来进行，欢迎交流指正～

请问“可以映射量化信息到转换后的模型的对应层，将信息写入gfpq_param_file 文件中”这个是怎么做的呀，量化好了之后通过什么方式把这个导出呢，有脚本和gfpq_param_file的示例吗？
