### ISSUE TITLE
yolov5量化训练有问题

### ISSUE THREAD

**Issue by yy2yy** [aovoc/nnieqat-pytorch#22]
（1）您好，我按照readme的介绍在yolov5的源码中加入量化处理训练时，会出现问题：训练迭代三个epoch后map急剧下降，如下图所示：
![image](https://user-images.githubusercontent.com/51770574/145916917-89ef4c8b-e56c-459e-a4c8-a8bfc0bc9e4e.png)
（2）加载第2个epoch的模型时，利用gpu加载可以，但是利用cpu加载就会出现如下错误；即使是利用第2个epoch的模型进行gpu检测，是检测不到任何结果的，返回值全是nan：
执行ckpt = torch.load(w, map_location=map_location)出现错误：
Error at driver init: 
[100] Call to cuInit results in CUDA_ERROR_NO_DEVICE:
（3）请问您能开源一下您的yolov5的量化训练代码吗？还请不吝赐教，谢谢啦！

**Comment by aovoc** [comment]
1) 需要先确定是yolov5 训练的问题还是量化训练的问题，可以进行以下操作：
- 单独训练yolov5，确认原始yolov5训练没有问题；
- test_cifar10.py训练（ nnieqat test文件夹下）。

2) 我没有碰到过，从报错信息看还是有进行cuda的初始化，有没有可能是部分cuda调用代码没有更改？
3) [https://github.com/aovoc/yolov5](https://github.com/aovoc/yolov5 ) 小作修改的yolov5训练代码，我基于此进行的量化训练。

**Comment by yy2yy** [comment]
非常感谢您百忙之中能够回复：

1.我用的U版的yolov5训练的，之前训练yolov5是完全没问题的，量化训练进行了如下修改，不知道这样修改是否正确，烦请指教！

（1）‍添加register_quantization_hook(model)
![image](https://user-images.githubusercontent.com/51770574/145956323-9e5cf87f-64e0-4314-a91f-809a525e7471.png)

（2）‍添加model&nbsp;=&nbsp;merge_freeze_bn(model)

![image](https://user-images.githubusercontent.com/51770574/145956491-223bfa41-242d-47ec-a65e-52cda1af0c70.png)

（3）添加model.apply(unquant_weight)
![image](https://user-images.githubusercontent.com/51770574/145956581-492bfda9-253f-4375-af88-eea7823a9bb6.png)

（4）添加如下：
![image](https://user-images.githubusercontent.com/51770574/145956699-880103c1-0fa9-439f-892e-646fc7f8770f.png)

2.我再研究一下这个问题。

3.如果1.中我的调用流程没问题的话，我再在您的yolov5版本上试一试；如果1.有什么错误的地方，还请您指教，非常感谢！

**Comment by MiaoTian123** [comment]
> （1）您好，我按照readme的介绍在yolov5的源码中加入量化处理训练时，会出现问题：训练迭代三个epoch后map急剧下降，如下图所示： ![image](https://user-images.githubusercontent.com/51770574/145916917-89ef4c8b-e56c-459e-a4c8-a8bfc0bc9e4e.png) （2）加载第2个epoch的模型时，利用gpu加载可以，但是利用cpu加载就会出现如下错误；即使是利用第2个epoch的模型进行gpu检测，是检测不到任何结果的，返回值全是nan： 执行ckpt = torch.load(w, map_location=map_location)出现错误： Error at driver init: [100] Call to cuInit results in CUDA_ERROR_NO_DEVICE: （3）请问您能开源一下您的yolov5的量化训练代码吗？还请不吝赐教，谢谢啦！

请问您最后训练结果对了么？精度有下降么？
