### ISSUE TITLE
量化后对于小目标检测得分特别低

### ISSUE THREAD

**Issue by northeastsquare** [aovoc/nnieqat-pytorch#5]
你好，我用darknet训练了yolov3后，转换到nnie，用nnie sample，修改类别为两类（人，人头），跑起来后，发现对于大目标person预测正常，但是对于小目标,人头，得分特别低，很多只有0.0?, 我把阈值设置为0.01才把这些框取出来。而在darknet转到caffe后，得分在0.3以上，一切正常。
请问这种现象，是nnie的量化方式导致的吗？使用您的代码，训练后，这种现象会好吗？谢谢

**Comment by MuhammadAsadJaved** [comment]
@northeastsquare   Hi,  Have you tried yolov3 quantization using this method?

**Comment by northeastsquare** [comment]
have not

**Comment by aovoc** [comment]
yolov5在coco上进行量化实验，使用nnieqat量化包能够提升小目标检测效果，实验结果见readme.

**Comment by northeastsquare** [comment]
谢谢，@aovoc  如果在Hi3559上不使用nnieqat量化包的结果在coco上跑一下，和使用过nnieqat的结果进行对比，更能看到效果

**Comment by northeastsquare** [comment]
其实我也不确定，对于有小目标，要使用0.01的阈值获取result,是因为
caffe模型使用ruyi studio量化，我哪里做错了？其实我也是再四检测类别数量、通道、yolo输出层的设置；
还是因为海思量化过程本身导致的。

**Comment by tensorflowt** [comment]
> 其实我也不确定，对于有小目标，要使用0.01的阈值获取result,是因为
> caffe模型使用ruyi studio量化，我哪里做错了？其实我也是再四检测类别数量、通道、yolo输出层的设置；
> 还是因为海思量化过程本身导致的。

请问，你有尝试作者的方法到海思的芯片上吗？
