### ISSUE TITLE
Quantization of Yolo and SSD

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [aovoc/nnieqat-pytorch#7]
Hi, 
     I have a few questions about the Yolov3 and SSD etc quantization.
1-How we can utilize this project for these state of the art methods? 
2-Are you planning to add any examples for these networks in the near future? 
3-Do we need to train the model using your proposed quantization method or we can also quantize pre-trained models? For example, if we have pre-trained yolov3.

**Comment by aovoc** [comment]
Added yolov5s coco results, refer to the README. 
1. Refer to Usage in README.
2. I will add examples gradually if needed.
3. Nnieqat is a quantize aware training package for nnie on pytorch, it's not a post-training quantization method. We can use nnieqat to finetune  a pre-trained model.
