### ISSUE TITLE
torch.nn.Hardswish报错

### ISSUE THREAD

**Issue by hbxtxjk** [aovoc/nnieqat-pytorch#8]
您好！在我这边跑test_cifar10.py例子时，在quantize.py文件 if quant_activation and isinstance(module, (torch.nn.ReLU, torch.nn.Hardswish, torch.nn.ELU)):这句话报错，显示torch.nn.Hardswish无定义，通过上pytorch官网，发现1.6之前的版本没有torch.nn.Hardswish相关说明，我把pytorch版本由1.5升级到1.6后能够正常使用了，麻烦您确认一下看看是否需要修改版本相关信息，谢谢！

**Comment by aovoc** [comment]
修改版本可以解决，我在pytorch 1.6上进行的测试。或者直接改代码，然后make install哈
